import os
from datetime import datetime
from typing import Dict, Any
from .state import PipelineState


class ReportGenerator:
    """Generates structured compliance reports."""
    
    def __init__(self, reports_dir: str = "reports"):
        self.reports_dir = reports_dir
        os.makedirs(reports_dir, exist_ok=True)
    
    def generate_report(self, state: PipelineState) -> PipelineState:
        """Generate a structured report from extracted data."""
        url = state["url"]
        extracted_data = state.get("extracted_data") or {}
        
        # Create report content
        report_content = self._create_report_content(url, extracted_data)
        
        # Save report to file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"company_report_{timestamp}.txt"
        report_path = os.path.join(self.reports_dir, report_filename)
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        state["report"] = report_content
        print(f"Report generated: {report_path}")
        
        return state
    
    def _create_report_content(self, url: str, extracted_data: Dict[str, Any]) -> str:
        """Create the report content."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"""
Company Information Report
==========================

Generated: {timestamp}
Source URL: {url}

EXTRACTED INFORMATION
---------------------

Company Name: {extracted_data.get('company_name', 'Not found')}
Contact Email: {extracted_data.get('contact_email', 'Not found')}
Phone Number: {extracted_data.get('phone_number', 'Not found')}
Address: {extracted_data.get('address', 'Not found')}
About Us: {extracted_data.get('about_us_text', 'Not found')}

EVIDENCE FILES
--------------

HTML Evidence: evidence/raw_*.html

EXTRACTION STATUS
-----------------

Validation Status: {'Validated' if extracted_data else 'Failed'}
Fields Extracted: {len([v for v in extracted_data.values() if v])}/5

---
Report generated by Compliance Evidence Pipeline
"""
        
        return report.strip()
